# Generated by Django 4.0.3 on 2022-03-31 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Имя')),
                ('usersurname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('password', models.CharField(max_length=32, verbose_name='Пароль')),
                ('date_of_birth', models.DateField(blank=True, verbose_name='Дата рождения')),
                ('photo', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d', verbose_name='Фото профиля')),
                ('user_login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Логин')),
            ],
        ),
    ]
