# Generated by Django 4.0.3 on 2022-03-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_remove_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo/%Y/%m/%d', verbose_name='Фото профиля'),
        ),
    ]
