# Generated by Django 4.0.3 on 2022-04-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('text', models.CharField(max_length=255)),
            ],
        ),
    ]
