# Generated by Django 4.0.3 on 2022-04-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_room_remove_message_text_message_date_message_room_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='value',
            field=models.TextField(),
        ),
    ]
